src/BTZ-Transports.API/Controllers/MotoristasController.cs
using AutoMapper;
using BTZ_Transports.API.ViewModels;
using BTZ_Transports.Negocio.Interfaces;
using BTZ_Transports.Negocio.Models;
using Microsoft.AspNetCore.Mvc;

namespace BTZ_Transports.API.Controllers
{
    [Route("[controller]")]
    public class MotoristasController : MainController
    {
        private readonly IMotoristaService _motoristaService;
        private readonly IMapper _mapper;
        public MotoristasController(INotificador notificador, IMotoristaService motoristaService, IMapper mapper) : base(notificador)
        {
            _motoristaService = motoristaService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var motoristas = _mapper.Map<IEnumerable<MotoristaViewModel>>(await _motoristaService.ObterMotoristas());
            return motoristas.Any() ?
                          View("Index", motoristas.ToList()) :
                           View("Index", Enumerable.Empty<MotoristaViewModel>());
        }

        [Route("criar-novo")]
        public IActionResult Criar()
        {
            return View("Criar");
        }

        [HttpPost("criar-motorista")]
        public async Task<IActionResult> Adicionar([FromForm] MotoristaViewModel veiculoViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Criar", veiculoViewModel);
            }
            else
            {
                await _motoristaService.Adicionar(_mapper.Map<Motorista>(veiculoViewModel));
                return RedirectToAction(nameof(Index));
            };
        }

        [Route("editar-motorista/{id}")]
        public async Task<ActionResult<MotoristaViewModel>> Editar(Guid id)
        {
            var motoristaViewModel = await _motoristaService.ObterPorId(id);
            if (id == null || motoristaViewModel == null)
            {
                return NotFound();
            }
 
            return View(_mapper.Map<MotoristaViewModel>(motoristaViewModel));
         }

        [HttpPost("editar-motorista/{id:guid}")]
        public async Task<IActionResult> Editar(Guid id, [FromForm] MotoristaViewModel MotoristaViewModel)
        {
            if (id != MotoristaViewModel.Id)
            {
                NotificarErro("O id informado não corresponde o mesmo que foi passado na query");
                return CustomResponse(MotoristaViewModel);
            }

            if (!ModelState.IsValid) return CustomResponse(ModelState);

            await _motoristaService.Atualizar(_mapper.Map<Motorista>(MotoristaViewModel));

            return RedirectToAction(nameof(Index));
        }

        [Route("excluir/{id}")] 
        public async Task<ActionResult<MotoristaViewModel>> Remover(Guid id)
        {
            var veiculoViewModel = await _motoristaService.ObterPorId(id);
            if (id == null || veiculoViewModel == null)
            {
                return NotFound();
            }

            return View(_mapper.Map<MotoristaViewModel>(veiculoViewModel));
        }

        [HttpPost("{id}"), ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ExcluirConfirmado(Guid id)
        {
            var veiculo = await _motoristaService.ObterPorId(id);
            if (veiculo == null) return NotFound();

            await _motoristaService.Remover(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/BTZ-Transports.API/Controllers/RegistroAbastrecimentoController.cs
using AutoMapper;
using BTZ_Transports.API.ViewModels;
using BTZ_Transports.Negocio.Interfaces;
using BTZ_Transports.Negocio.Models;
using Microsoft.AspNetCore.Mvc;

namespace BTZ_Transports.API.Controllers
{
    [Route("[controller]")]
    public class RegistroAbastecimentoController : MainController
    {
        private readonly IRegistroAbastecimentoService _registroAbastecimentoService;
        private readonly IMotoristaService _motoristaService;
        private readonly IVeiculoService _veiculoService;
        private readonly IMapper _mapper;
        public RegistroAbastecimentoController(INotificador notificador, IVeiculoService veiculoRepository, IMotoristaService motoristaService, IRegistroAbastecimentoService RegistroAbastecimentoRepository, IMapper mapper) : base(notificador)
        {
            _registroAbastecimentoService = RegistroAbastecimentoRepository;
            _mapper = mapper;
            _motoristaService = motoristaService;
            _veiculoService = veiculoRepository;
        }

        public async Task<IActionResult> Index()
        {
            var motoristas = _mapper.Map<IEnumerable<RegistroAbastecimentoViewModel>>(await _registroAbastecimentoService.ObterRegistroAbastecimentos());
            return motoristas.Any() ?
                          View("Index", motoristas.ToList()) :
                           View("Index", Enumerable.Empty<RegistroAbastecimentoViewModel>());
        }

        [Route("criar-novo")]
        public async Task<IActionResult> Criar()
        {
            ViewBag.Motoristas = _mapper.Map<IEnumerable<MotoristaViewModel>>(await _motoristaService.ObterMotoristas()).ToList();
            ViewBag.Veiculo = _mapper.Map<IEnumerable<VeiculoViewModel>>(await _veiculoService.ObterVeiculos()).ToList();
            return View("Criar");
        }

        [HttpPost("criar-registro-abastecimento")]
        public async Task<IActionResult> Adicionar([FromForm] RegistroAbastecimentoViewModel veiculoViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Criar", veiculoViewModel);
            }
            else
            {
                await _registroAbastecimentoService.Adicionar(_mapper.Map<RegistroAbastecimento>(veiculoViewModel));
                return RedirectToAction(nameof(Index));
            }
        }

        [Route("editar-motorista/{id}")]
        public async Task<ActionResult<MotoristaViewModel>> Editar(Guid id)
        {
            var motoristaViewModel = await _motoristaService.ObterPorId(id);
            if (id == null || motoristaViewModel == null)
            {
                return NotFound();
            }

            return View(_mapper.Map<MotoristaViewModel>(motoristaViewModel));
        }

        [HttpPost("editar-motorista/{id:guid}")]
        public async Task<IActionResult> Editar(Guid id, [FromForm] MotoristaViewModel MotoristaViewModel)
        {
            if (id != MotoristaViewModel.Id)
            {
                NotificarErro("O id informado não corresponde o mesmo que foi passado na query");
                return CustomResponse(MotoristaViewModel);
            }

            if (!ModelState.IsValid) return CustomResponse(ModelState);

            await _motoristaService.Atualizar(_mapper.Map<Motorista>(MotoristaViewModel));

            return RedirectToAction(nameof(Index));
        }
    }
}

src/BTZ-Transports.API/Controllers/VeiculosController.cs
using AutoMapper;
using BTZ_Transports.API.ViewModels;
using BTZ_Transports.Negocio.Interfaces;
using BTZ_Transports.Negocio.Models;
using Microsoft.AspNetCore.Mvc;

namespace BTZ_Transports.API.Controllers
{
    [Route("[controller]")]
    public class VeiculosController : MainController
    {
        private readonly IVeiculoService _veiculoService;
        private readonly IMapper _mapper;
        public VeiculosController(INotificador notificador, IVeiculoService veiculoRepository, IMapper mapper) : base(notificador)
        {
            _veiculoService = veiculoRepository;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var veiculos = _mapper.Map<IEnumerable<VeiculoViewModel>>(await _veiculoService.ObterVeiculos());
            return veiculos.Any() ?
                          View("Index", veiculos.ToList()) :
                           View("Index", Enumerable.Empty<VeiculoViewModel>());
        }
         

        [Route("criar-novo")]
        public IActionResult Criar()
        {
            return View("Criar");
        }

        [HttpPost("criar-veiculo")]
        [HttpPost]
        public async Task<ActionResult<VeiculoViewModel>> Adicionar([FromForm] VeiculoViewModel veiculoViewModel)
        {
            if ( !ModelState.IsValid) return View("Criar", veiculoViewModel);

            await _veiculoService.Adicionar(_mapper.Map<Veiculo>(veiculoViewModel));
             
            return RedirectToAction(nameof(Index));
        }


        [Route("editar-veiculo/{id}")]
        public async Task<ActionResult<VeiculoViewModel>> Editar(Guid id)
        {
            var veiculoViewModel = await ObterPorId(id);
            if (id == null || veiculoViewModel == null)
            {
                return NotFound();
            }

            return View(_mapper.Map<VeiculoViewModel>(veiculoViewModel));

        }

        [HttpPost("editar-veiculo/{id:guid}")]
        public async Task<ActionResult<VeiculoViewModel>> Editar(Guid id, [FromForm] VeiculoViewModel veiculoViewModel)
        {
            if (id != veiculoViewModel.Id)
            {
                NotificarErro("O id informado não corresponde o mesmo que foi passado na query");
                return CustomResponse(veiculoViewModel);
            }

            if (!ModelState.IsValid) return CustomResponse(ModelState);

            await _veiculoService.Atualizar(_mapper.Map<Veiculo>(veiculoViewModel));
            return RedirectToAction(nameof(Index));
        }

        [HttpDelete("{id:guid}")]
        public async Task<ActionResult<VeiculoViewModel>> Remover(Guid id)
        {
            var veiculo = await _veiculoService.ObterPorId(id);
            if (veiculo == null) return NotFound();

            await _veiculoService.Remover(id);

            return CustomResponse(veiculo);
        }

        private async Task<VeiculoViewModel> ObterPorId(Guid id)
        {
            var veiculoViewModel = await _veiculoService.ObterPorId(id);
            if (veiculoViewModel == null) return null;

            return _mapper.Map<VeiculoViewModel>(veiculoViewModel);
        }
    }
}

src/BTZ-Transports.API/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"] - BTZ-Transports</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" />
    </environment>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BTZ-Transports</a>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Veiculos" asp-action="Index">Veiculos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Motoristas" asp-action="Index">Motoristas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RegistroAbastecimento" asp-action="Index">Regitros de Abastecimento</a>
                        </li> 
                    </ul>
    
                </div>
            </div>
        </nav>
    </header>

    <div class="container"> 
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="d-flex justify-content-between">
                <div class="text-start">
                    Informações da empresa BTZ Transports
                    • Endereço: Av. das Palmeiras, 40 – Maringá – PR
                    • Contato: (44) 3246-4144 / (44) 99999-8888 (whats) - sac@btztransports.com.br
                    • Horário de atendimento: seg/sex – 08h00 – 22h00
                </div>
              
              
            </div>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
        <script src="~/js/site.js"></script>
        <script src="~/js/cep.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.min.js"></script>
    </environment>
</body>
</html>